### ISSUE TITLE
Using with Hassio

### ISSUE THREAD

**Issue by dror3go** [mortenmathiasen/piir#1]
First of all, thanks for publishing this nice little tool.

I'm a Home Assistant newbie - and so I decided to use [Hassio](https://www.home-assistant.io/hassio/) on my Raspberry Pi 4 Model B (as opposed to [manual installation](https://www.home-assistant.io/docs/installation/raspberry-pi/)).
Is it possible to use PIIR when working with Hass.io? I'm not sure how I can `apt install` the required packages and compile the software when working like this, and in the other solution - addons are not available when using a manual installation of HA.

Thanks for your help

**Comment by mortenmathiasen** [comment]
No problem. You can `apt install` both when using Hass.io and when using the manual installation of HA. Home Assistant [installation](https://www.home-assistant.io/installation/) comes in more versions, basically with or without [Docker containers](https://www.docker.com/). Due to performance I run mine without Docker, installation called Home Assistant Core. For the new high performance RPI4 the recommended [guide](https://www.home-assistant.io/installation/raspberrypi) will install with Docker, installation is called Hassio. 

Installing PIIR into Home Assistant Core or Hassio is easy. All you need to do is to log into your RPI4 and then follow the guide to compile and install the tool as described at [PIIR](https://github.com/mortenmathiasen/piir). Then you need to configure Home Assistant to use PIIR as described in PIIR's [Wiki](https://github.com/mortenmathiasen/piir/wiki/Home-Assistant). Home Assistant Core version is configured by following this [guide](https://www.home-assistant.io/docs/configuration/). Hassio version is configured by following this [guide](https://www.home-assistant.io/getting-started/configuration/).
